### ISSUE TITLE
Github PR 및 Issue 템플릿 셋팅 의견 제시

### ISSUE THREAD

**Issue by Choyoonyoung98** [ExchangeDiary/ExchangeDiary_iOS#6]
더 명시적인 협업을 위해 PR 및 Issue 작성 템플릿 자동화를 도입하는 건 어떨까요?

관련 레퍼런스 첨부합니다: http://naver.me/xfa0yuhT

Issue 템플릿의 경우 아래와 유사한 형태가 될 것 같습니다.

```
## 목표
//정의된 기능 및 화면 이미지가 있다면 추가로 첨부

## 체크 리스트
- [ ]
- [ ]
- [ ]

## 참고
```

**Comment by jeon-soyeong** [comment]
오 저도 체크리스트 사용하는거 좋아하는데 자동화 도입하면 더 편리하고 좋을 것 같아요! 😃
